In [4]:
print("sdada")

sdada


In [2]:
import numpy as np
import tensorflow as tf

In [19]:
v1 = tf.Variable(tf.constant(3.0, shape=[4]),dtype = 'float32')

In [10]:
print(v1)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 2., 2., 2.], dtype=float32)>


In [16]:
v2 = tf.Variable(np.ones(shape = [4,3]),dtype = 'float32')
v3 = v2*3.0

In [20]:
print(v3)

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(4, 3), dtype=float32)


In [18]:
print(type(v1).__name__)

ResourceVariable
