In [28]:
import numpy as np
import tensorflow as tf
import pandas as pd
import random
from sklearn.decomposition import PCA

from tensorflow.keras import layers

from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline
import requests

# Fixing the seed to obtain consistent random values during multiple runs

from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential

import tensorflow.keras.backend as K
    
def fix_random_seed(seed):
    """ Setting the random seed of various libraries """
    try:
        np.random.seed(seed)
    except NameError:
        print("Warning: Numpy is not imported. Setting the seed for Numpy failed.")
    try:
        tf.random.set_seed(seed)
    except NameError:
        print("Warning: TensorFlow is not imported. Setting the seed for TensorFlow failed.")
    try:
        random.seed(seed)
    except NameError:
        print("Warning: random module is not imported. Setting the seed for random failed.")

# Fixing the random seed
fix_random_seed(4321)
print("TensorFlow version: {}".format(tf.__version__))

TensorFlow version: 2.16.1


In [29]:
# Section 3.1

import requests
import pandas as pd
import tensorflow as tf

# Retrieve the data
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
r = requests.get(url)

with open('iris.data', 'wb') as f:
  f.write(r.content)

# Read the data in
iris_df = pd.read_csv('iris.data', header=None)

# Set the column names
iris_df.columns = ['sepal_length', 'sepal_width', 'petal_width', 'petal_length', 'label']
print("asddadsad",iris_df.label.unique())

# Convert labels to integers
iris_df["label"] = iris_df["label"].map({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})

# Shuffle the data
iris_df = iris_df.sample(frac=1.0, random_state=4321)

# Normalize the features by subtracting the mean
x = iris_df[["sepal_length", "sepal_width", "petal_width", "petal_length"]]
x = x - x.mean(axis=0)

# Converting integer labels to one-hot vectors
y = tf.one_hot(iris_df["label"], depth=3)

iris_df.head()

asddadsad ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


sepal_length  sepal_width  petal_width  petal_length  label
31            5.4          3.4          1.5           0.4      0
23            5.1          3.3          1.7           0.5      0
70            5.9          3.2          4.8           1.8      1
100           6.3          3.3          6.0           2.5      2
44            5.1          3.8          1.9           0.4      0

In [30]:
print(x)

     sepal_length  sepal_width  petal_width  petal_length
31      -0.443333        0.346    -2.258667     -0.798667
23      -0.743333        0.246    -2.058667     -0.698667
70       0.056667        0.146     1.041333      0.601333
100      0.456667        0.246     2.241333      1.301333
44      -0.743333        0.746    -1.858667     -0.798667
..            ...          ...          ...           ...
113     -0.143333       -0.554     1.241333      0.801333
91       0.256667       -0.054     0.841333      0.201333
146      0.456667       -0.554     1.241333      0.701333
124      0.856667        0.246     1.941333      0.901333
61       0.056667       -0.054     0.441333      0.301333

[150 rows x 4 columns]


In [31]:
print(y)

tf.Tensor(
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 

In [42]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow.keras.backend as k

k.clear_session()

model = Sequential([
    Dense(32, activation='relu',input_shape = (4,)),
    Dense(16, activation='relu'),
    Dense(3,activation = 'softmax')]
)

model.summary()


# Compiling the model with a loss function, an optimizer and a performance metric
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

# Fitting the model with data
model.fit(x, y, batch_size=100, epochs=25)


C:\Users\saxen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 739 (2.89 KB)

 Trainable params: 739 (2.89 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - acc: 0.3622 - loss: 1.2703
Epoch 2/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.3700 - loss: 1.2249
Epoch 3/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.4300 - loss: 1.1824 
Epoch 4/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.4367 - loss: 1.1425
Epoch 5/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.4322 - loss: 1.1049 
Epoch 6/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.4478 - loss: 1.0694 
Epoch 7/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.4600 - loss: 1.0359 
Epoch 8/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.4600 - loss: 1.0042 
Epoch 9/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.4600 - loss: 0.9738 
Epoch 10/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.4633 - loss: 0.9448 
Epoch 11/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.4756 - loss: 0.9172 
Epoch 12/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.5189 - loss: 0.8908
Epoch 13/25
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.540

In [43]:
from tensorflow.keras.layers import Input,Dense,Concatenate

In [44]:
k.clear_session()

In [45]:
inp1 = Input(shape=(4,))
inp2 = Input(shape=(2,))

In [46]:
out1 = Dense(16,activation='relu')(inp1)
out2 = Dense(16,activation='relu')(inp2)

In [47]:
out = Concatenate(axis=1)([out1,out2])

In [48]:
out = Dense(16,activation='relu')(out)

In [49]:
out = Dense(3,activation='softmax')(out)

In [51]:
model = Model(inputs=[inp1,inp2],outputs = out)

In [52]:
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam', metrics = ['acc'])

In [53]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 4)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ input_layer_1 (InputLayer)    │ (None, 2)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 16)                │              80 │ input_layer[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 16)                │              48 │ input_layer_1[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate (Concatenate)     │ (None, 32)                │               0 │ dense[0][0], dense_1[0][0] │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 16)                │             528 │ concatenate[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 3)                 │              51 │ dense_2[0][0]              │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 707 (2.76 KB)

 Trainable params: 707 (2.76 KB)

 Non-trainable params: 0 (0.00 B)

In [58]:
from sklearn.decomposition import PCA
pca_model = PCA(n_components = 2, random_state = 4321)
x_pca = pca_model.fit_transform(x)

In [59]:
model.fit([x,x_pca],y,batch_size=64,epochs=25)

Epoch 1/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.2661 - loss: 1.1312
Epoch 2/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.3603 - loss: 1.0843 
Epoch 3/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.4017 - loss: 1.0402 
Epoch 4/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.4875 - loss: 0.9984  
Epoch 5/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.6857 - loss: 0.9590 
Epoch 6/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.7779 - loss: 0.9219 
Epoch 7/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7904 - loss: 0.8868  
Epoch 8/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8010 - loss: 0.8531 
Epoch 9/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8135 - loss: 0.8202 
Epoch 10/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8135 - loss: 0.7885 
Epoch 11/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8043 - loss: 0.7583 
Epoch 12/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8149 - loss: 0.7300 
Epoch 13/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0

In [66]:
# Example: Predicting on the same inputs used for training
predictions = model.predict([x, x_pca])

print(predictions)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.7606735  0.19316676 0.04615968]
 [0.7402833  0.20641816 0.05329843]
 [0.07508285 0.30711472 0.6178024 ]
 [0.01413671 0.14069498 0.8451683 ]
 [0.74685407 0.20826238 0.04488356]
 [0.04208348 0.2287341  0.7291824 ]
 [0.7988414  0.17138638 0.02977222]
 [0.07061461 0.28483313 0.6445523 ]
 [0.02254113 0.16373216 0.81372666]
 [0.20436893 0.513519   0.28211215]
 [0.18582529 0.5419996  0.27217507]
 [0.75672317 0.19876505 0.04451176]
 [0.08014853 0.40151837 0.51833314]
 [0.0811803  0.3659945  0.5528253 ]
 [0.00555251 0.14569898 0.84874856]
 [0.19475982 0.53008574 0.2751545 ]
 [0.22570004 0.555044   0.21925597]
 [0.02897363 0.22308294 0.74794334]
 [0.8027461  0.16751419 0.02973968]
 [0.7777329  0.18405752 0.03820955]
 [0.06566117 0.3553699  0.57896894]
 [0.03927667 0.20162362 0.7590998 ]
 [0.02872112 0.21607456 0.75520426]
 [0.04880883 0.31910083 0.6320904 ]
 [0.7915486  0.1764334  0.032018  ]
 [0.01033307 0.20810638 0.78156054]
 [0.0743629  0.34822372 0.

In [69]:
# Section 3.1
# Code listing 3.3

from tensorflow.keras import layers

class MulBiasDense(layers.Layer):
    """ The layer with the new multiplicative bias we want to test """
    
    def __init__(self, units=32, activation=None):
        """ Defines various hyperparameters of the layer"""
        
        super(MulBiasDense, self).__init__()
        self.units = units
        self.activation = activation
    
    def build(self, input_shape):
        """ Defines the parameters (weights and biases)"""
        
        self.w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='glorot_uniform',
                                 trainable=True)
        self.b = self.add_weight(shape=(self.units,),
                                 initializer='glorot_uniform',
                                 trainable=True)
        self.b_mul = self.add_weight(shape=(self.units,),
                                     initializer='glorot_uniform',
                                     trainable=True)

    def call(self, inputs):
        """ Defines the computations that happen in the layer"""
        
        out = (tf.matmul(inputs, self.w) + self.b) * self.b_mul
        return layers.Activation(self.activation)(out)
        


In [70]:
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
import tensorflow.keras.backend as K
import tensorflow as tf

inp = Input(shape=(4,))

out = MulBiasDense(32,'relu')(inp)
out = MulBiasDense(16,'relu')(out)

out = Dense(3,'softmax')(out)

model = Model(inputs=inp, outputs=out)
# Compiling the model with a loss function, an optimizer and a performance metric
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 4)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ mul_bias_dense (MulBiasDense)        │ (None, 32)                  │             192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ mul_bias_dense_1 (MulBiasDense)      │ (None, 16)                  │             544 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 3)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 787 (3.07 KB)

 Trainable params: 787 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [71]:
# Section 3.1
# Fitting the model with data
model.fit(x, y, batch_size=64, epochs=25)

Epoch 1/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - acc: 0.4883 - loss: 1.0986
Epoch 2/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6685 - loss: 1.0961 
Epoch 3/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6829 - loss: 1.0937 
Epoch 4/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - acc: 0.6829 - loss: 1.0913  
Epoch 5/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6829 - loss: 1.0888 
Epoch 6/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6829 - loss: 1.0863 
Epoch 7/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6829 - loss: 1.0836 
Epoch 8/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.6829 - loss: 1.0807 
Epoch 9/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6829 - loss: 1.0778 
Epoch 10/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.6829 - loss: 1.0747 
Epoch 11/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.6829 - loss: 1.0715 
Epoch 12/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6829 - loss: 1.0682 
Epoch 13/25
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.700